// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace WinUIApplication
{
    [default_interface]
    runtimeclass SerialUtil : Microsoft.UI.Xaml.Controls.Page
    {
        SerialUtil();
    }
}
